### ISSUE TITLE
Error during server-start

### ISSUE THREAD

**Issue by LLLOOOMMM** [justin-guan/discord-announcer#26]
Hello, 
today i installed node.js, mongodb and this bot because i wanted to use it. During startup i get the following error:

I am running W10 20H2 and node v14.16.0-x64.

`npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path D:\Program Files\nodejs\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'D:\Program Files\nodejs\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bitfarm\AppData\Roaming\npm-cache\_logs\2021-03-21T21_33_13_520Z-debug.log

D:\Program Files\nodejs>npm start

> discord-announcer@3.0.0-beta prestart D:\Program Files\nodejs
> node src/scripts/directoryCheck.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'fs-extra'
Require stack:
- D:\Program Files\nodejs\src\scripts\directoryCheck.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\Program Files\nodejs\src\scripts\directoryCheck.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\Program Files\\nodejs\\src\\scripts\\directoryCheck.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-announcer@3.0.0-beta prestart: `node src/scripts/directoryCheck.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-announcer@3.0.0-beta prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bitfarm\AppData\Roaming\npm-cache\_logs\2021-03-21T21_33_30_890Z-debug.log`

I attached the log. If you need more information, I am happy to provide it.
[2021-03-21T21_33_30_890Z-debug.log](https://github.com/justin-guan/discord-announcer/files/6178445/2021-03-21T21_33_30_890Z-debug.log)

**Comment by justin-guan** [comment]
This project isn't really maintained anymore. I'd recommend that you check out https://github.com/justin-guan/discord-doggo instead. It's a rewritten version of this bot that's more up to date. I decided to rewrite this bot so that some of the code was less messy, and it has near feature parity. I believe Discord has also changed some of the APIs so I'm not confident that this bot will work 100% properly (another reason to give https://github.com/justin-guan/discord-doggo a try instead). Additionally, the set up has less dependencies, so it should be a bit easier to set up (no need to install/build ffmpeg). I've updated the documentation to point people toward that new repo instead.

However, if you really want to run this project instead (I highly recommend https://github.com/justin-guan/discord-doggo instead though), then this error is saying you have missing dependencies. My guess is that your `npm install` didn't complete successfully. You could try deleting the `node_modules` directory, and then running `npm install` again and see if any dependency fails. Since you're running Windows, there's some Windows specific dependencies that the `npm install` log should point out, namely the Microsoft Visual Studio with the Desktop Development with C++ workload (`msvc`). Have you set that up? If not, then I would recommend looking at [this](https://stackoverflow.com/a/59882818) for how to set it up. Additionally, I believe [python](https://www.python.org/downloads/) is also one of the external build dependencies that `npm install` will log an error for if it's missing.

Note, that if you do decide to use https://github.com/justin-guan/discord-doggo instead, `msvc` is still necessary. And if you're running into issues running that project, feel free to open up an issue in that repo instead, and I'll do my best to help out!

**Comment by LLLOOOMMM** [comment]
Hi,

thank you for replying. Im going to try discord-doggo instead👍
